# Generated by Django 5.2.15 on 2026-06-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_status', models.CharField(default='paid', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.group')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructor')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouttype')),
            ],
        ),
    ]
