# Generated by Django 5.2.15 on 2026-06-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('valid_to', models.DateField()),
                ('applicable_to', models.CharField(default='all', max_length=100)),
            ],
        ),
    ]
