# Generated by Django 5.2.15 on 2026-06-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('equipment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_cycle', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(default='group', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('clients', models.ManyToManyField(blank=True, to='users.client')),
                ('instructors', models.ManyToManyField(to='users.instructor')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouttype')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.group')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.gymhall')),
                ('instructor_ids', models.ManyToManyField(to='users.instructor')),
            ],
        ),
    ]
