# Generated by Django 5.2.15 on 2026-06-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_companyhistory_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='companyhistory',
            options={},
        ),
        migrations.AddField(
            model_name='companyhistory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
